### ISSUE TITLE
App gets stuck downloading departures

### ISSUE THREAD

**Issue by werebus** [umts/pvta-multiplatform#345] opened 2017-03-31 20:37 UTC
A few times recently, I've gone to (re?)start the app and was greeted by this

![screenshot_20170331-161902](https://cloud.githubusercontent.com/assets/240275/24568446/0aa982f4-1630-11e7-91d6-47f3ef3706ef.png)

Pulsing on the screen over and over again.

Killing the app and restarting it fixes the problem.

**Comment by akaplo** [comment] 2017-03-31 21:58
I might've experienced that as well.  Can you confirm whether this was after you switched apps while pvtrack was on the Stop page?

My issue, FWIW, is as follows:
If I'm on the Stop page and background the app for any period of time, upon my return I get a "downloading departures" spinner that pulses over the stop page as it looked when I left.  Interestingly, I think it pulses as many times as the app would've autorefreshed if it was in the foreground. So, if I've got autorefresh set to 15s and leave the app for like 2 hours, that's about 480 pulses before anything happens (eek!) I kept forgetting to open an issue.

**Comment by werebus** [comment] 2017-04-01 00:57
I think you're right. I usually encounter this in the afternoons after I've
used the app that morning. About 8 hours later.

Just now I was able to get it to happen less severely after leaving it for
about half an hour.

**Comment by akaplo** [comment] 2017-04-01 02:38
I just realized (while I was debugging this in the emulator and couldn't reproduce it) that I had made a "hotfix" in [345c23d](https://github.com/umts/pvta-multiplatform/commit/c0684166fda6bb765ad92383cef91add175b1f0a#diff-ab9a6fe1a4c091d88734a8110345c23d), which hasn't been deployed to the Play Store yet.

That said, I'm working on a more permanent fix now.

**Comment by akaplo** [comment] 2017-04-01 02:45
The actual issue here is that the `ionViewWillLeave` lifecycle hook (which we use to cancel the autorefresh) doesn't get called when the native app gets backgrounded or closed; it only gets called when the page is navigated away from to _another page in the app_.

I'm implementing Cordova's lifecycle hooks `pause` and `resume` as a solution.

**Comment by akaplo** [comment] 2017-04-04 18:50
Closed via #349.

**Closed as completed by akaplo** 2017-04-04 18:50 UTC
Labels: bug, v2
