### ISSUE TITLE
Buses estimated time issue

### ISSUE THREAD

**Issue by arbass22** [umts/pvta-multiplatform#444] opened 2017-11-03 19:59 UTC
At first I thought that it was missing the 9:10am bus, but realized that the bus got labeled with an incorrect estimated time and then got put in the wrong spot in the list.  These are all the same bus, so not sure why the 9:10 would be assigned the much later estimated time. 
![img_1129](https://user-images.githubusercontent.com/10891729/32393454-e4cfeaca-c0af-11e7-92f6-c80ac8aa74d6.jpg)

**Comment by sherson** [comment] 2017-11-06 02:35
Thanks for reporting this. Route 35 has three "blocks": 351, 352, and 353. 351 isn't recognized by the AVL system as Route 35. We don't know the cause, but we'll investigate further and contact the vendor about it. 

This isn't a bug with this app (it appears to be a data problem that's messing up PVTA's real-time), but leaving this issue open.

**Comment by sherson** [comment] 2017-12-08 17:45
Resolved with the last Avail publish

**Closed as completed by sherson** 2017-12-08 17:45 UTC
Labels: dependent on other issue(s)
